user_register:
    path: /api/user/register
    controller: App\Controller\User\UserController::create
    methods: POST

user_login:
    path: /api/user/login
    controller: App\Controller\User\UserController::login
    methods: POST

user_logout:
    path: /api/user/logout
    controller: App\Controller\User\UserController::logout
    methods: POST

singer_create:
    path: /api/singer
    controller: App\Controller\Singer\SingerController::create
    methods: POST

song_upload:
    path: /api/song
    controller: App\Controller\Song\SongController::upload
    methods: POST

song_stream:
    path: /api/song/{artistId}/{songId}/stream
    controller: App\Controller\Song\SongController::streamSong
    methods: GET
    requirements:
        artistId: \d+
        songId: \d+

singer_playlist:
    path: /api/singer/{singerId}/playlist
    controller: App\Controller\Singer\SingerController::getPlaylist
    methods: GET
    requirements:
        singerId: \d+

song_latest:
    path: /api/song/latest
    controller: App\Controller\Song\SongController::getLatestSongs
    methods: GET

genre_list:
    path: /api/genre
    controller: App\Controller\Genre\GenreController::list
    methods: GET

user_profile:
    path: /api/user/profile
    controller: App\Controller\User\UserController::profile
    methods: GET

api_song_favorite_add:
    path: /api/song/{songId}/favorite
    methods: POST
    controller: App\Controller\Song\SongController::addToFavorites

api_song_favorite_remove:
    path: /api/song/{songId}/favorite
    methods: DELETE
    controller: App\Controller\Song\SongController::removeFromFavorites

api_song_user_favorite:
    path: /api/song/user/favorite
    methods: GET
    controller: App\Controller\Song\SongController::getUserFavoriteSongs

api_user_playlist_create:
    path: /api/user/playlists
    methods: POST
    controller: App\Controller\UserPlaylist\UserPlaylistController::create

api_user_playlist_list:
    path: /api/user/playlists
    methods: GET
    controller: App\Controller\UserPlaylist\UserPlaylistController::getUserPlaylists

api_user_playlist_add_song:
    path: /api/user/playlists/{id}/songs
    methods: POST
    controller: App\Controller\UserPlaylist\UserPlaylistController::addSong

api_user_playlist_get:
    path: /api/user/playlists/{id}
    methods: GET
    controller: App\Controller\UserPlaylist\UserPlaylistController::get

api_release_create:
    path: /api/release
    methods: POST
    controller: App\Controller\Release\ReleaseController::create

api_release_get:
    path: /api/release/{id}
    methods: GET
    controller: App\Controller\Release\ReleaseController::get

api_singer_songs:
    path: /api/singer/{singerId}/songs
    methods: GET
    controller: App\Controller\Singer\SingerController::getSongs

api_singer_info:
    path: /api/singer/{singerId}
    methods: GET
    controller: App\Controller\Singer\SingerController::getSingerInfo

api_singer_subscribe:
    path: /api/subscribe/singer/{singerId}
    methods: POST
    controller: App\Controller\Subscribe\SubscribeController::subscribe

api_singer_unsubscribe:
    path: /api/subscribe/singer/{singerId}
    methods: DELETE
    controller: App\Controller\Subscribe\SubscribeController::unsubscribe

api_release_by_singer:
    path: /api/releases/singer/{singerId}
    methods: GET
    controller: App\Controller\Release\ReleaseController::getBySinger

api_future_release_by_singer:
    path: /api/releases/singer/{singerId}/future
    methods: GET
    controller: App\Controller\Release\ReleaseController::getBySingerFuture

api_search:
    path: /api/search
    methods: GET
    controller: App\Controller\Search\SearchController::search

api_increment_song:
    path: /api/song/{songId}/increment
    methods: GET
    controller: App\Controller\Song\SongController::incrementPlayCount

api_user_playlist_delete:
    path: /api/user/playlists/{playlistId}
    methods: DELETE
    controller: App\Controller\UserPlaylist\UserPlaylistController::delete

api_user_playlist_delete_song:
    path: /api/user/playlists/{playlistId}/{songId}
    methods: DELETE
    controller: App\Controller\UserPlaylist\UserPlaylistController::removeSong

api_user_history_playlist:
    path: /api/user/history
    methods: GET
    controller: App\Controller\ListeningHistory\ListeningHistoryController::history

api_admin_genres:
    path: /api/admin/genres
    methods: GET
    controller: App\Controller\Admin\Genre\GenreController::genres

api_admin_genres_create:
    path: /api/admin/genres
    methods: POST
    controller: App\Controller\Admin\Genre\GenreController::createGenre

api_admin_genres_delete:
    path: /api/admin/genres/{id}
    methods: DELETE
    controller: App\Controller\Admin\Genre\GenreController::deleteGenre

api_admin_custom_genres_delete:
    path: /api/admin/custom-genres
    methods: DELETE
    controller: App\Controller\Admin\Genre\GenreController::deleteCustomGenre

api_admin_custom_genres_promote:
    path: /api/admin/custom-genres/promote
    methods: POST
    controller: App\Controller\Admin\Genre\GenreController::promoteCustomGenre

api_admin_statistics:
    path: /api/admin/statistics
    methods: GET
    controller: App\Controller\Admin\AdminController::statistics

api_song_delete:
    path: /api/song/{songId}
    methods: DELETE
    controller: App\Controller\Song\SongController::deleteSong

api_release_delete:
    path: /api/release/{releaseId}
    methods: DELETE
    controller: App\Controller\Release\ReleaseController::deleteRelease

api_user_song_et:
    path: /api/user/song
    methods: GET
    controller: App\Controller\UserSong\UserSongController::getUserSongs

api_user_song_upload:
    path: /api/user/song
    methods: POST
    controller: App\Controller\UserSong\UserSongController::uploadSongs

api_user_song_delete:
    path: /api/user/song/{songId}
    methods: DELETE
    controller: App\Controller\UserSong\UserSongController::deleteUserSong
